### ISSUE TITLE
Fixed picker blocks when hidden

### ISSUE THREAD

**Issue by RanzQ** [dgrubelic/material-design-lite#21]
I had an issue that my clicks were blocked by the fixed picker. This happened after I had dynamically added the picker to DOM. After opening and hiding it wasn't blocking anymore though. I made a little change in `mdl-datepicker__widget` style which fixed it for me:

```
    &.is-fixed {
      transform: translate(0, -100%);
```

Does MD define it should be `-50%`?

**Comment by dgrubelic** [comment]
No, it doesn't. That should be -100% to fix the issue you were having. Thanks for reporting. I'll made a fix and update official PR. Thanks for reporting it.

**Comment by dgrubelic** [comment]
Have you pulled latest version of `datepicker` branch? The thing is that widget element should be removed once it is closed.
I can't reproduce this issue but i put `transform: translate(0, -100%);` anyway.

**Comment by RanzQ** [comment]
@dgrubelic As I described it happened only after I dynamically added the picker element to DOM and upgraded it, after closing it didn't block anymore. I'm very busy atm but when I have time I can setup some codepens for this and the button position problem I was having.

**Comment by dgrubelic** [comment]
I must say, i have no idea where this problem you're having is coming from. I just created a demo for dynamically added date pickers and each time i tested everything worked as expected. Actually, i use this component in angular app (with ui-router, thus providing dynamically added pickers), and there are no problems either. 
As i said, since widget is removed after it is hidden, there is no chance of this bug ever happening. Please provide workable CodePen with bug demo, until then this stays closed and off my focus.
